const HOST = (window.origin + window.location.pathname).replace(/\/index.html$/, '/')

export default [
    {
        pid: 'RecentlySubmitted',
        name: '最近提交',
        name_en: 'Recently Submitted',
        order: 0,
        children: [
{
                id: 'LearningCell',
                name: '细胞课堂',
                name_en: 'LearningCell',
                author: 'AUTO',
                openUrl: 'https://gordensun.github.io/LearningCell/',
                githubUrl: 'https://github.com/GordenSun/LearningCell',
                image: HOST + 'images/LearningCell.webp',
            },
{
                id: 'PSU-VR',
                name: '室内vr',
                name_en: 'PSU-VR',
                author: 'AUTO',
                openUrl: 'https://psu-vr.herokuapp.com/',
                githubUrl: 'https://github.com/andrewwoan/PSU-VR',
                image: HOST + 'images/PSU-VR.webp',
            },
{
                id: 'sooahs-room-folio',
                name: '房间',
                name_en: 'sooahs-room-folio',
                author: 'AUTO',
                openUrl: 'https://www.sooahs-room-folio.com/',
                githubUrl: 'https://github.com/andrewwoan/sooahs-room-folio',
                image: HOST + 'images/sooahs-room-folio.webp',
            },
{
                id: 'r3f-webgpu-post-processing',
                name: 'webgpu 后期渲染',
                name_en: 'r3f-webgpu-post-processing',
                author: 'AUTO',
                openUrl: 'https://r3f-webgpu-post-processing.vercel.app/',
                githubUrl: 'https://github.com/ektogamat/r3f-webgpu-starter',
                image: HOST + 'images/r3f-webgpu-post-processing.webp',
            },
{
                id: 'DeviceShowcase',
                name: '电脑',
                name_en: 'DeviceShowcase',
                author: 'AUTO',
                openUrl: 'https://tympanus.net/Tutorials/DeviceShowcase/',
                githubUrl: 'https://github.com/repalash/threepipe-device-mockup-codrops',
                image: HOST + 'images/DeviceShowcase.webp',
            },
{
                id: 'bellas-park',
                name: '公园',
                name_en: 'bellas-park',
                author: 'AUTO',
                openUrl: 'https://www.bellas-park.com/',
                githubUrl: 'https://github.com/andrewwoan/bellas-park',
                image: HOST + 'images/bellas-park.webp',
            },
{
                id: 'FluffyGrass',
                name: '草地',
                name_en: 'FluffyGrass',
                author: 'AUTO',
                openUrl: 'https://fluffygrass.vercel.app/',
                githubUrl: 'https://github.com/thebenezer/FluffyGrass',
                image: HOST + 'images/FluffyGrass.webp',
            },
{
                id: 'wawa-baking',
                name: '烘培房间',
                name_en: 'wawa-baking',
                author: 'AUTO',
                openUrl: 'https://baking.wawasensei.dev/',
                githubUrl: 'https://github.com/wass08/r3f-baking',
                image: HOST + 'images/wawa-baking.webp',
            },
{
                id: 'codrops-noise-transition',
                name: '易拉罐',
                name_en: 'codrops-noise-transition',
                author: 'AUTO',
                openUrl: 'https://tympanus.net/Development/TextureTransition/',
                githubUrl: 'https://github.com/mohAmineBrs/codrops-noise-transition/',
                image: HOST + 'images/codrops-noise-transition.webp',
            },
{
                id: 'zen-robot-garden',
                name: '割草机器人',
                name_en: 'zen-robot-garden',
                author: 'AUTO',
                openUrl: 'https://robin7331.github.io/zen-robot-garden/',
                githubUrl: 'https://github.com/robin7331/zen-robot-garden',
                image: HOST + 'images/zen-robot-garden.webp',
            },
{
                id: 'Abdul-Wasay-008',
                name: '太阳系',
                name_en: 'Abdul-Wasay-008',
                author: 'AUTO',
                openUrl: 'https://atlas26.vercel.app/dashboard',
                githubUrl: 'https://github.com/Abdul-Wasay-008/Atlas26',
                image: HOST + 'images/Abdul-Wasay-008.webp',
            },
{
                id: 'icraft',
                name: 'icraft',
                name_en: 'icraft',
                author: 'AUTO',
                openUrl: 'https://icraft.design/app/player/dmqSz2F-niKujD94cPb7-Zsa9zIH2Ggt',
                githubUrl: 'https://github.com/gantFDT/icraft',
                image: HOST + 'images/icraft.webp',
            },
{
                id: 'bike-demo-threejs',
                name: 'bike-demo-threejs',
                name_en: 'bike-demo-threejs',
                author: 'AUTO',
                openUrl: 'https://bike-demo-threejs.vercel.app/',
                githubUrl: 'https://github.com/Kirilbt/bike-demo-threejs',
                image: HOST + 'images/bike-demo-threejs.webp',
            },
{
                id: 'off-axis-sneaker',
                name: '图像识别控制',
                name_en: 'off-axis-sneaker',
                author: 'AUTO',
                openUrl: 'https://off-axis-sneaker.bolt.host/',
                githubUrl: 'https://github.com/icurtis1/off-axis-sneaker',
                image: HOST + 'images/off-axis-sneaker.webp',
            },
{
                id: 'tiny-world-builder',
                name: 'tiny-world-builder',
                name_en: 'tiny-world-builder',
                author: 'AUTO',
                openUrl: 'https://tinyworld.build/',
                githubUrl: 'https://github.com/jasonkneen/tiny-world-builder',
                image: HOST + 'images/tiny-world-builder.webp',
            },
{
                id: 'Interactive-Styling-Canvas',
                name: '切换衣服',
                name_en: 'Interactive-Styling-Canvas',
                author: 'AUTO',
                openUrl: 'https://tympanus.net/Development/InteractiveStylingUI/',
                githubUrl: 'https://github.com/kaberikram/Interactive-Styling-Canvas',
                image: HOST + 'images/Interactive-Styling-Canvas.webp',
            },
{
                id: 'r3f-unshift-effect',
                name: 'unshift-effect',
                name_en: 'r3f-unshift-effect',
                author: 'AUTO',
                openUrl: 'https://nemutas.github.io/r3f-unshift-effect/',
                githubUrl: 'https://github.com/nemutas/r3f-unshift-effect',
                image: HOST + 'images/r3f-unshift-effect.webp',
            },
{
                id: 'third-person-controller-splat',
                name: '高斯漫游',
                name_en: 'third-person-controller-splat',
                author: 'AUTO',
                openUrl: 'https://third-person-character-controller.netlify.app/',
                githubUrl: 'https://github.com/icurtis1/third-person-controller-splat',
                image: HOST + 'images/aa.webp',
            },
{
                id: 'sat-hunter',
                name: '卫星地图下载',
                name_en: 'sat-hunter',
                author: 'AUTO',
                openUrl: 'https://knight-l.github.io/sat-hunter/',
                githubUrl: 'https://github.com/knight-L/sat-hunter',
                image: HOST + 'images/sat-hunter.webp',
            },
{
                id: 'marble-runner',
                name: 'marble-runner',
                name_en: 'marble-runner',
                author: 'AUTO',
                openUrl: 'https://marble-runner.vercel.app/',
                githubUrl: 'https://github.com/panterathehacker/marble-runner',
                image: HOST + 'images/marble-runner.webp',
            },
{
                id: 'articraft',
                name: 'ai 建模动画',
                name_en: 'articraft',
                author: 'AUTO',
                openUrl: 'https://articraft3d.github.io/#overview',
                githubUrl: 'https://github.com/mattzh72/articraft',
                image: HOST + 'images/articraft.webp',
            },
{
                id: 'hologram-particles',
                name: 'hologram-particles',
                name_en: 'hologram-particles',
                author: 'AUTO',
                openUrl: 'https://hologram-particles.vercel.app/',
                githubUrl: 'https://github.com/cortiz2894/hologram-particles',
                image: HOST + 'images/hologram-particles.webp',
            },
{
                id: 'aholo-viewer',
                name: '高斯渲染',
                name_en: 'aholo-viewer',
                author: 'AUTO',
                openUrl: 'https://aholojs.dev/zh-CN/',
                githubUrl: 'https://github.com/manycoretech/aholo-viewer',
                image: HOST + 'images/aholo-viewer.webp',
            },
{
                id: 'comfort-website',
                name: '3d主页网站',
                name_en: 'comfort-website',
                author: 'AUTO',
                openUrl: 'https://john-and-patricias-romantic-comfort.vercel.app/',
                githubUrl: 'https://github.com/andrewwoan/john-and-patricias-romantic-comfort-website',
                image: HOST + 'images/comfort-website.webp',
            },
{
                id: 'three-fenestra',
                name: 'three-fenestra',
                name_en: 'three-fenestra',
                author: 'AUTO',
                openUrl: 'https://three-fenestra.codedgar.com/',
                githubUrl: 'https://github.com/codedgar/three-fenestra',
                image: HOST + 'images/three-fenestra.webp',
            },
{
                id: 'cymatics-labs',
                name: '音频粒子',
                name_en: 'cymatics-labs',
                author: 'AUTO',
                openUrl: 'https://cymatics-labs.vercel.app/',
                githubUrl: 'https://github.com/Sidmaz666/cymatics-labs',
                image: HOST + 'images/cymatics-labs.webp',
            },
{
                id: 'SysMocap',
                name: '数字虚拟人',
                name_en: 'SysMocap',
                author: 'AUTO',
                openUrl: 'https://github.com/xianfei/SysMocap',
                githubUrl: 'https://github.com/xianfei/SysMocap',
                image: HOST + 'images/SysMocap.webp',
            },
{
                id: 'demo-threejs-chinamap',
                name: '下钻地图',
                name_en: 'demo-threejs-chinamap',
                author: 'AUTO',
                openUrl: 'https://github.com/chemistwang/demo-threejs-chinamap',
                githubUrl: 'https://github.com/chemistwang/demo-threejs-chinamap',
                image: HOST + 'images/demo-threejs-chinamap.webp',
            },
{
                id: 'gta7',
                name: 'gta7',
                name_en: 'gta7',
                author: 'AUTO',
                openUrl: 'https://depixeled-chris.github.io/gta7/',
                githubUrl: 'https://github.com/depixeled-chris/gta7',
                image: HOST + 'images/gta7.webp',
            },
{
                id: 'cat-planet',
                name: 'cat-planet',
                name_en: 'cat-planet',
                author: 'AUTO',
                openUrl: 'https://qq598516797-dotcom.github.io/cat-planet/',
                githubUrl: 'https://github.com/qq598516797-dotcom/cat-planet',
                image: HOST + 'images/cat-planet.webp',
            },
{
                id: 'house-builder',
                name: 'house-builder',
                name_en: 'house-builder',
                author: 'AUTO',
                openUrl: 'https://ch-bas.github.io/threejs-sims-house-builder/',
                githubUrl: 'https://github.com/ch-bas/threejs-sims-house-builder',
                image: HOST + 'images/house-builder.webp',
            },
{
                id: 'tang-changan',
                name: 'tang-changan',
                name_en: 'tang-changan',
                author: 'AUTO',
                openUrl: 'https://github.com/andyhuo520/tang-changan',
                githubUrl: 'https://github.com/andyhuo520/tang-changan',
                image: HOST + 'images/tang-changan.webp',
            },
{
                id: 'Rose_flower',
                name: 'Rose_flower',
                name_en: 'Rose_flower',
                author: 'AUTO',
                openUrl: 'https://wake-bikila-dev.github.io/Rose_flower/',
                githubUrl: 'https://github.com/wake-bikila-dev/Rose_flower',
                image: HOST + 'images/Rose_flower.webp',
            },
{
                id: 'dtilesConverter',
                name: '3dtiles Converter',
                name_en: '3dtiles Converter',
                author: 'AUTO',
                openUrl: 'https://github.com/fanvanzh/3dtiles',
                githubUrl: 'https://github.com/fanvanzh/3dtiles',
                image: HOST + 'images/dtilesConverter.webp',
            },
{
                id: 'webgpu-perf',
                name: 'webgpu-perf',
                name_en: 'webgpu-perf',
                author: 'AUTO',
                openUrl: 'https://r3f-webgpu-perf.vercel.app/',
                githubUrl: 'https://github.com/ektogamat/r3f-webgpu-perf',
                image: HOST + 'images/webgpu-perf.webp',
            },
{
                id: 'Lens-Flare',
                name: 'Lens-Flare',
                name_en: 'Lens-Flare',
                author: 'AUTO',
                openUrl: 'https://ultimate-lens-flare.vercel.app/',
                githubUrl: 'https://github.com/ektogamat/R3F-Ultimate-Lens-Flare',
                image: HOST + 'images/Lens-Flare.webp',
            },
{
                id: 'topoexport',
                name: '框选地图导出白模',
                name_en: 'topoexport',
                author: 'AUTO',
                openUrl: 'https://app.topoexport.com/',
                githubUrl: 'https://github.com/ArunSahadeo/TopoExporter',
                image: HOST + 'images/topoexport.webp',
            },
            {
                id: 'yyhg',
                name: '北京优悦幻光科技',
                name_en: 'yyhg',
                author: 'AUTO',
                openUrl: 'https://z2586300277.github.io/yyhg/',
                githubUrl: 'https://github.com/z2586300277/yyhg',
                image: HOST + 'images/yyhg.webp',
            },
{
                id: 'scenic-digital',
                name: '数字人',
                name_en: 'scenic-digital',
                author: 'AUTO',
                openUrl: 'https://scenic.yueguichao.cn/#',
                githubUrl: 'https://github.com/front-yue/scenic-digital',
                image: HOST + 'images/scenic-digital.webp',
            },
{
                id: 'vrm-game',
                name: 'vrm-游戏',
                name_en: 'vrm-game',
                author: 'AUTO',
                openUrl: 'https://norio.github.io/vrm-game-starter/',
                githubUrl: 'https://github.com/norio/vrm-game-starter',
                image: HOST + 'images/vrm-game.webp',
            },
{
                id: 'openThree',
                name: '开源三维',
                name_en: 'openThree',
                author: 'AUTO',
                openUrl: 'https://z2586300277.github.io/three-cesium-examples',
                githubUrl: 'https://github.com/z2586300277/three-cesium-examples',
                image: HOST + 'images/openThree.webp',
            },
{
                id: 'rubiks-rubrics',
                name: 'rubiks-rubrics',
                name_en: 'rubiks-rubrics',
                author: 'AUTO',
                openUrl: 'https://leereilly.net/rubiks-rubrics/',
                githubUrl: 'https://github.com/leereilly/rubiks-rubrics',
                image: HOST + 'images/rubiks-rubrics.webp',
            },
{
                id: '3d_tools',
                name: '3D相关工具集',
                name_en: '3d_tools',
                author: 'AUTO',
                openUrl: 'https://z2586300277.github.io/3d_tools/',
                githubUrl: 'https://github.com/z2586300277/3d_tools',
                image: HOST + 'images/3d_tools.webp',
            },
{
                id: 'ecctrl_ecctrl',
                name: 'ecctrl_ecctrl',
                name_en: 'ecctrl_ecctrl',
                author: 'AUTO',
                openUrl: 'https://ecctrl.app/',
                githubUrl: 'https://github.com/pmndrs/ecctrl',
                image: HOST + 'images/ecctrl_ecctrl.webp',
            },
{
                id: 'collider-forge',
                name: 'collider-forge',
                name_en: 'collider-forge',
                author: 'AUTO',
                openUrl: 'https://github.com/hh-hang/collider-forge',
                githubUrl: 'https://github.com/hh-hang/collider-forge',
                image: HOST + 'images/collider-forge.webp',
            },
{
                id: 'pixijs',
                name: 'pixijs',
                name_en: 'pixijs',
                author: 'AUTO',
                openUrl: 'https://pixijs.com/showcase',
                githubUrl: 'https://github.com/pixijs/pixijs',
                image: HOST + 'images/pixijs.webp',
            },
            {
                id: 'fable5world',
                name: 'fable5world',
                name_en: 'fable5world',
                author: 'AUTO',
                openUrl: 'https://dc5fzrbo8ssfx.cloudfront.net/laas/',
                githubUrl: 'https://github.com/Braffolk/fable5-world-demo',
                image: HOST + 'images/fable5world.webp',
            },
{
                id: 'cesium-player-controller',
                name: 'cesium 第三人称控制器',
                name_en: 'cesium-player-controller',
                author: 'AUTO',
                openUrl: 'https://hh-hang.github.io/cesium-player-controller/',
                githubUrl: 'https://github.com/hh-hang/cesium-player-controller',
                image: HOST + 'images/cesium-player-controller.webp',
            },
{
                id: 'GeoLibre',
                name: 'GeoLibre',
                name_en: 'GeoLibre',
                author: 'AUTO',
                openUrl: 'https://geolibre.app/demo/',
                githubUrl: 'https://github.com/opengeos/GeoLibre',
                image: HOST + 'images/GeoLibre.webp',
            },
{
                id: 'ABot-Earth',
                name: 'ABot-Earth',
                name_en: 'ABot-Earth',
                author: 'AUTO',
                openUrl: 'https://abot-earth.amap.com/',
                githubUrl: 'https://github.com/amap-cvlab/ABot-Earth-0.5',
                image: HOST + 'images/ABot-Earth.webp',
            },
{
                id: 'cesium-ez-tree',
                name: 'cesium-ez-tree',
                name_en: 'cesium-ez-tree',
                author: 'AUTO',
                openUrl: 'https://xiaobai-grow.github.io/cesium-ez-tree/',
                githubUrl: 'https://github.com/Xiaobai-grow/cesium-ez-tree',
                image: HOST + 'images/cesium-ez-tree.webp',
            },
{
                id: 'threejswaterpro',
                name: 'threejswaterpro',
                name_en: 'threejswaterpro',
                author: 'AUTO',
                openUrl: 'https://www.threejswaterpro.com/',
                githubUrl: 'https://github.com/dgreenheck/webgpu-water',
                image: HOST + 'images/threejswaterpro.webp',
            },
{
                id: 'messenger-copy',
                name: 'messenger-copy',
                name_en: 'messenger-copy',
                author: 'AUTO',
                openUrl: 'https://messenger.abeto.co/',
                githubUrl: 'https://github.com/arafays/messenger-copy',
                image: HOST + 'images/messenger-copy.webp',
            },
{
                id: 'tellux',
                name: 'tellux',
                name_en: 'tellux',
                author: 'AUTO',
                openUrl: 'https://tellux.cyanfish.site/sandcastle.html',
                githubUrl: 'https://github.com/cyanfish-x/tellux',
                image: HOST + 'images/tellux.webp',
            },
{
                id: 'de-bees',
                name: 'de-bees',
                name_en: 'de-bees',
                author: 'AUTO',
                openUrl: 'https://de-bees.vercel.app/',
                githubUrl: 'https://github.com/snyderb-de/de-bees',
                image: HOST + 'images/de-bees.jpg',
            },
{
                id: 'cyanfishcesium',
                name: 'cyanfish-cesium',
                name_en: 'cyanfish-cesium',
                author: 'AUTO',
                openUrl: 'https://demo.cyanfish.site/cesium',
                githubUrl: 'https://github.com/cyanfish-x/tellux',
                image: HOST + 'images/cyanfishcesium.webp',
            },
{
                id: 'procedural-spider',
                name: 'procedural-spider',
                name_en: 'procedural-spider',
                author: 'AUTO',
                openUrl: 'https://proceduralspider.netlify.app/',
                githubUrl: 'https://github.com/majidmanzarpour/threejs-procedural-spider',
                image: HOST + 'images/procedural-spider.webp',
            },
{
                id: 'ThreeJS_Portfolio',
                name: 'ThreeJS_Portfolio',
                name_en: 'ThreeJS_Portfolio',
                author: 'AUTO',
                openUrl: 'https://three-js-portfolio-rust-beta.vercel.app/',
                githubUrl: 'https://github.com/Plattnericus/ThreeJS_Portfolio',
                image: HOST + 'images/ThreeJS_Portfolio.webp',
            },
{
                id: 'lego-stylized-nature',
                name: 'lego-stylized-nature',
                name_en: 'lego-stylized-nature',
                author: 'AUTO',
                openUrl: 'https://lego-stylized-nature.vercel.app/',
                githubUrl: 'https://github.com/hexianWeb/lego-stylized-nature',
                image: HOST + 'images/lego-stylized-nature.webp',
            },
{
                id: 'map3d-build',
                name: '生成3D白膜',
                name_en: 'map3d-build',
                author: 'AUTO',
                openUrl: 'https://map.fleet.im/',
                githubUrl: 'https://github.com/cartesiancs/map3d',
                image: HOST + 'images/map3d-build.webp',
            },
{
                id: 'day-night-digital-twins',
                name: '数字校园黑夜白天',
                name_en: 'day-night-digital-twins',
                author: 'AUTO',
                openUrl: 'https://gcat.cc/demo/park',
                githubUrl: 'https://github.com/GhostCatcg/day-night-digital-twins',
                image: HOST + 'images/day-night-digital-twins.webp',
            },
{
                id: 'ode-to-yosemite',
                name: 'ode-to-yosemite',
                name_en: 'ode-to-yosemite',
                author: 'AUTO',
                openUrl: 'https://ode-to-yosemite.vercel.app/',
                githubUrl: 'https://github.com/shlokkhemani/ode-to-yosemite',
                image: HOST + 'images/ode-to-yosemite.webp',
            },
{
                id: 'collectivetrajectories',
                name: 'collectivetrajectories',
                name_en: 'collectivetrajectories',
                author: 'AUTO',
                openUrl: 'https://jeonghopark.de/collectivetrajectories/',
                githubUrl: 'https://github.com/jeonghopark/Collective-Trajectories',
                image: HOST + 'images/collectivetrajectories.jpg',
            },
{
                id: 'threejsskypro',
                name: 'threejsskypro',
                name_en: 'threejsskypro',
                author: 'AUTO',
                openUrl: 'https://threejsskypro.com/',
                githubUrl: 'https://github.com/threejsskypro/threejsskypro',
                image: HOST + 'images/threejsskypro.webp',
            },
{
                id: 'lius1314-china-map',
                name: 'lius1314-china-map',
                name_en: 'lius1314-china-map',
                author: 'AUTO',
                openUrl: 'https://www.npmjs.com/package/@lius1314/china-map-3d-designer',
                githubUrl: 'https://github.com/z2586300277/three-cesium-examples',
                image: HOST + 'images/lius1314-china-map.webp',
            },
{
                id: 'modkeys',
                name: 'modkeys',
                name_en: 'modkeys',
                author: 'AUTO',
                openUrl: 'https://modkeys.vercel.app/',
                githubUrl: 'https://github.com/thebuggeddev/modkeys',
                image: HOST + 'images/modkeys.webp',
            },
{
                id: 'silhouette-pom',
                name: 'silhouette-pom',
                name_en: 'silhouette-pom',
                author: 'AUTO',
                openUrl: 'https://skyeshark.github.io/threejs-silhouette-pom/',
                githubUrl: 'https://github.com/SkyeShark/threejs-silhouette-pom',
                image: HOST + 'images/silhouette-pom.webp',
            },
{
                id: 'weisdevice-project',
                name: 'weisdevice-project',
                name_en: 'weisdevice-project',
                author: 'AUTO',
                openUrl: 'https://www.weisdevice.xyz/',
                githubUrl: 'https://github.com/wehwayne2/weisdevice-project',
                image: HOST + 'images/weisdevice-project.webp',
            },
{
                id: 'challenge-geo',
                name: 'challenge-geo',
                name_en: 'challenge-geo',
                author: 'AUTO',
                openUrl: 'https://x-challenge-geo.vercel.app/',
                githubUrl: 'https://github.com/wehwayne2/x-challenge-geo',
                image: HOST + 'images/challenge-geo.webp',
            },
{
                id: 'battlefield-editor',
                name: 'battlefield-editor',
                name_en: 'battlefield-editor',
                author: 'AUTO',
                openUrl: 'https://yazelin.github.io/battlefield-editor/',
                githubUrl: 'https://github.com/yazelin/battlefield-editor',
                image: HOST + 'images/battlefield-editor.webp',
            },
{
                id: 'overpass-turbo',
                name: '城市交通路网等geojson',
                name_en: 'overpass-turbo',
                author: 'AUTO',
                openUrl: 'https://overpass-turbo.eu/',
                githubUrl: 'https://github.com/overpass/overpass-turbo',
                image: HOST + 'images/overpass-turbo.webp',
            },
{
                id: 'texturesFree',
                name: '免费贴图',
                name_en: 'texturesFree',
                author: 'AUTO',
                openUrl: 'https://www.textures.com/free',
                githubUrl: 'https://github.com/textures/textures',
                image: HOST + 'images/texturesFree.webp',
            },
{
                id: 'geo-downloader',
                name: '地区geo-下载器',
                name_en: 'geo-downloader',
                author: 'AUTO',
                openUrl: 'https://geodownloader.pages.dev/',
                githubUrl: 'https://github.com/gaopengbin/geo-downloader',
                image: HOST + 'images/geo-downloader.webp',
            },
{
                id: 'TerrainStudio',
                name: 'TerrainStudio',
                name_en: 'TerrainStudio',
                author: 'AUTO',
                openUrl: 'https://terrains.zyfod.dev/',
                githubUrl: 'https://github.com/nalbam/TerrainStudio',
                image: HOST + 'images/TerrainStudio.webp',
            },
{
                id: 'china-heritage-3d',
                name: 'china-heritage-3d',
                name_en: 'china-heritage-3d',
                author: 'AUTO',
                openUrl: 'https://architecture-iota-khaki.vercel.app/',
                githubUrl: 'https://github.com/xyiqq/china-heritage-3d',
                image: HOST + 'images/china-heritage-3d.webp',
            },
{
                id: 'RippleAquarium',
                name: 'RippleAquarium',
                name_en: 'RippleAquarium',
                author: 'AUTO',
                openUrl: 'https://seanwong17.github.io/RippleAquarium/',
                githubUrl: 'https://github.com/SeanWong17/RippleAquarium',
                image: HOST + 'images/RippleAquarium.webp',
            },
{
                id: 'threejs-procedural-dungeon',
                name: 'threejs-procedural-dungeon',
                name_en: 'threejs-procedural-dungeon',
                author: 'AUTO',
                openUrl: 'https://procedural-dungeon.netlify.app/',
                githubUrl: 'https://github.com/majidmanzarpour/threejs-procedural-dungeon',
                image: HOST + 'images/threejs-procedural-dungeon.webp',
            },
{
                id: 'storyai-3d-director-desk',
                name: '3D导演台-Ai视频',
                name_en: 'storyai-3d-director-desk',
                author: 'AUTO',
                openUrl: 'https://github.com/jiguang132/storyai-3d-director-desk',
                githubUrl: 'https://github.com/jiguang132/storyai-3d-director-desk',
                image: HOST + 'images/storyai-3d-director-desk.webp',
            },
{
                id: 'HiCAD',
                name: 'HiCAD',
                name_en: 'HiCAD',
                author: 'AUTO',
                openUrl: 'https://hicad.mvtable.com/',
                githubUrl: 'https://github.com/MrXujiang/HiCAD',
                image: HOST + 'images/HiCAD.webp',
            },
{
                id: 'my-virtual-world',
                name: 'my-virtual-world',
                name_en: 'my-virtual-world',
                author: 'AUTO',
                openUrl: 'https://myvirtualworld.ai/',
                githubUrl: 'https://github.com/eliautobot/my-virtual-world',
                image: HOST + 'images/my-virtual-world.webp',
            },
{
                id: 'fmhy',
                name: '资源库',
                name_en: 'fmhy',
                author: 'AUTO',
                openUrl: 'https://fmhy.net/',
                githubUrl: 'https://github.com/fmhy/edit',
                image: HOST + 'images/fmhy.webp',
            },
{
                id: 'ApexForge',
                name: 'AI 建模',
                name_en: 'ApexForge',
                author: 'AUTO',
                openUrl: 'http://apexforge.turntip.cn/',
                githubUrl: 'https://github.com/MrXujiang/ApexForge',
                image: HOST + 'images/ApexForge.webp',
            },
{
                id: 'Three-Object-Sculptor',
                name: 'codexthreejs 插件',
                name_en: 'Three-Object-Sculptor',
                author: 'AUTO',
                openUrl: 'https://3dship.harrysoftware.com/',
                githubUrl: 'https://github.com/vinhhien112/Three.js-Object-Sculptor-Codex-Plugin',
                image: HOST + 'images/Three.js-Object-Sculptor-Codex-Plugin.webp',
            },
{
                id: 'lowpoly-tree-generator',
                name: 'lowpoly-tree-generator',
                name_en: 'lowpoly-tree-generator',
                author: 'AUTO',
                openUrl: 'https://rand.monster/editor/tree',
                githubUrl: 'https://github.com/rand-monster/lowpoly-tree-generator',
                image: HOST + 'images/lowpoly-tree-generator.webp',
            },
{
                id: 'gltf-optimizer',
                name: '模型压缩',
                name_en: 'gltf-optimizer',
                author: 'AUTO',
                openUrl: 'https://gltf-optimizer.simondev.io/',
                githubUrl: 'https://github.com/juunini/gltf-optimizer',
                image: HOST + 'images/gltf-optimizer.webp',
            },
{
                id: 'skyline-run',
                name: 'skyline-run',
                name_en: 'skyline-run',
                author: 'AUTO',
                openUrl: 'https://skyline-run.vercel.app',
                githubUrl: 'https://github.com/anshaneja5/skyline-run',
                image: HOST + 'images/skyline-run.webp',
            },
{
                id: 'SeedOcean',
                name: 'SeedOcean',
                name_en: 'SeedOcean',
                author: 'AUTO',
                openUrl: 'https://reed-soul.github.io/SeedOcean/',
                githubUrl: 'https://github.com/reed-soul/SeedOcean',
                image: HOST + 'images/SeedOcean.webp',
            },
{
                id: 'MisterPrada',
                name: 'MisterPrada',
                name_en: 'MisterPrada',
                author: 'AUTO',
                openUrl: 'https://github.com/MisterPrada',
                githubUrl: 'https://github.com/MisterPrada/singularity',
                image: HOST + 'images/MisterPrada.webp',
            },
            {
                id: 'three-auto',
                name: 'three-auto',
                name_en: 'three-auto',
                author: 'AUTO',
                openUrl: 'https://three-auto.vercel.app/',
                githubUrl: 'https://github.com/flowers-10/three-auto',
                image: HOST + 'images/three-auto.webp',
            },
            {
                id: 'KallkaGoMy_website',
                name: 'KallkaGoMy_website',
                name_en: 'KallkaGoMy_website',
                author: 'AUTO',
                openUrl: 'https://my-website-kallka.vercel.app/#work',
                githubUrl: 'https://github.com/KallkaGo/My_website',
                image: HOST + 'images/KallkaGoMy_website.webp',
            },
        ]
    }
]