const HOST = (window.origin + window.location.pathname).replace(/\/index.html$/, '/')

export default [
    {
        pid: 'RecentlySubmitted',
        name: '最近提交',
        name_en: 'Recently Submitted',
        order: 0,
        children: [
{
                id: 'LearningCell',
                name: '细胞课堂',
                name_en: 'LearningCell',
                author: 'AUTO',
                openUrl: 'https://gordensun.github.io/LearningCell/',
                githubUrl: 'https://github.com/GordenSun/LearningCell',
                image: HOST + 'images/LearningCell.webp',
            },
{
                id: 'PSU-VR',
                name: '室内vr',
                name_en: 'PSU-VR',
                author: 'AUTO',
                openUrl: 'https://psu-vr.herokuapp.com/',
                githubUrl: 'https://github.com/andrewwoan/PSU-VR',
                image: HOST + 'images/PSU-VR.webp',
            },
{
                id: 'sooahs-room-folio',
                name: '房间',
                name_en: 'sooahs-room-folio',
                author: 'AUTO',
                openUrl: 'https://www.sooahs-room-folio.com/',
                githubUrl: 'https://github.com/andrewwoan/sooahs-room-folio',
                image: HOST + 'images/sooahs-room-folio.webp',
            },
{
                id: 'r3f-webgpu-post-processing',
                name: 'webgpu 后期渲染',
                name_en: 'r3f-webgpu-post-processing',
                author: 'AUTO',
                openUrl: 'https://r3f-webgpu-post-processing.vercel.app/',
                githubUrl: 'https://github.com/ektogamat/r3f-webgpu-starter',
                image: HOST + 'images/r3f-webgpu-post-processing.webp',
            },
{
                id: 'DeviceShowcase',
                name: '电脑',
                name_en: 'DeviceShowcase',
                author: 'AUTO',
                openUrl: 'https://tympanus.net/Tutorials/DeviceShowcase/',
                githubUrl: 'https://github.com/repalash/threepipe-device-mockup-codrops',
                image: HOST + 'images/DeviceShowcase.webp',
            },
{
                id: 'bellas-park',
                name: '公园',
                name_en: 'bellas-park',
                author: 'AUTO',
                openUrl: 'https://www.bellas-park.com/',
                githubUrl: 'https://github.com/andrewwoan/bellas-park',
                image: HOST + 'images/bellas-park.webp',
            },
{
                id: 'FluffyGrass',
                name: '草地',
                name_en: 'FluffyGrass',
                author: 'AUTO',
                openUrl: 'https://fluffygrass.vercel.app/',
                githubUrl: 'https://github.com/thebenezer/FluffyGrass',
                image: HOST + 'images/FluffyGrass.webp',
            },
{
                id: 'wawa-baking',
                name: '烘培房间',
                name_en: 'wawa-baking',
                author: 'AUTO',
                openUrl: 'https://baking.wawasensei.dev/',
                githubUrl: 'https://github.com/wass08/r3f-baking',
                image: HOST + 'images/wawa-baking.webp',
            },
{
                id: 'codrops-noise-transition',
                name: '易拉罐',
                name_en: 'codrops-noise-transition',
                author: 'AUTO',
                openUrl: 'https://tympanus.net/Development/TextureTransition/',
                githubUrl: 'https://github.com/mohAmineBrs/codrops-noise-transition/',
                image: HOST + 'images/codrops-noise-transition.webp',
            },
{
                id: 'zen-robot-garden',
                name: '割草机器人',
                name_en: 'zen-robot-garden',
                author: 'AUTO',
                openUrl: 'https://robin7331.github.io/zen-robot-garden/',
                githubUrl: 'https://github.com/robin7331/zen-robot-garden',
                image: HOST + 'images/zen-robot-garden.webp',
            },
{
                id: 'Abdul-Wasay-008',
                name: '太阳系',
                name_en: 'Abdul-Wasay-008',
                author: 'AUTO',
                openUrl: 'https://atlas26.vercel.app/dashboard',
                githubUrl: 'https://github.com/Abdul-Wasay-008/Atlas26',
                image: HOST + 'images/Abdul-Wasay-008.webp',
            },
            {
                id: 'icraft',
                name: 'icraft',
                name_en: 'icraft',
                author: 'AUTO',
                openUrl: 'https://icraft.design/app/player/dmqSz2F-niKujD94cPb7-Zsa9zIH2Ggt',
                githubUrl: 'https://github.com/gantFDT/icraft',
                image: HOST + 'images/icraft.webp',
            },
{
                id: 'bike-demo-threejs',
                name: 'bike-demo-threejs',
                name_en: 'bike-demo-threejs',
                author: 'AUTO',
                openUrl: 'https://bike-demo-threejs.vercel.app/',
                githubUrl: 'https://github.com/Kirilbt/bike-demo-threejs',
                image: HOST + 'images/bike-demo-threejs.webp',
            },
{
                id: 'off-axis-sneaker',
                name: '图像识别控制',
                name_en: 'off-axis-sneaker',
                author: 'AUTO',
                openUrl: 'https://off-axis-sneaker.bolt.host/',
                githubUrl: 'https://github.com/icurtis1/off-axis-sneaker',
                image: HOST + 'images/off-axis-sneaker.webp',
            },
{
                id: 'tiny-world-builder',
                name: 'tiny-world-builder',
                name_en: 'tiny-world-builder',
                author: 'AUTO',
                openUrl: 'https://tinyworld.build/',
                githubUrl: 'https://github.com/jasonkneen/tiny-world-builder',
                image: HOST + 'images/tiny-world-builder.webp',
            },
{
                id: 'Interactive-Styling-Canvas',
                name: '切换衣服',
                name_en: 'Interactive-Styling-Canvas',
                author: 'AUTO',
                openUrl: 'https://tympanus.net/Development/InteractiveStylingUI/',
                githubUrl: 'https://github.com/kaberikram/Interactive-Styling-Canvas',
                image: HOST + 'images/Interactive-Styling-Canvas.webp',
            },
{
                id: 'r3f-unshift-effect',
                name: 'unshift-effect',
                name_en: 'r3f-unshift-effect',
                author: 'AUTO',
                openUrl: 'https://nemutas.github.io/r3f-unshift-effect/',
                githubUrl: 'https://github.com/nemutas/r3f-unshift-effect',
                image: HOST + 'images/r3f-unshift-effect.webp',
            },
{
                id: 'third-person-controller-splat',
                name: '高斯漫游',
                name_en: 'third-person-controller-splat',
                author: 'AUTO',
                openUrl: 'https://third-person-character-controller.netlify.app/',
                githubUrl: 'https://github.com/icurtis1/third-person-controller-splat',
                image: HOST + 'images/aa.webp',
            },
            {
                id: 'sat-hunter',
                name: '卫星地图下载',
                name_en: 'sat-hunter',
                author: 'AUTO',
                openUrl: 'https://knight-l.github.io/sat-hunter/',
                githubUrl: 'https://github.com/knight-L/sat-hunter',
                image: HOST + 'images/sat-hunter.webp',
            },
{
                id: 'marble-runner',
                name: 'marble-runner',
                name_en: 'marble-runner',
                author: 'AUTO',
                openUrl: 'https://marble-runner.vercel.app/',
                githubUrl: 'https://github.com/panterathehacker/marble-runner',
                image: HOST + 'images/marble-runner.webp',
            },
{
                id: 'articraft',
                name: 'ai 建模动画',
                name_en: 'articraft',
                author: 'AUTO',
                openUrl: 'https://articraft3d.github.io/#overview',
                githubUrl: 'https://github.com/mattzh72/articraft',
                image: HOST + 'images/articraft.webp',
            },
{
                id: 'hologram-particles',
                name: 'hologram-particles',
                name_en: 'hologram-particles',
                author: 'AUTO',
                openUrl: 'https://hologram-particles.vercel.app/',
                githubUrl: 'https://github.com/cortiz2894/hologram-particles',
                image: HOST + 'images/hologram-particles.webp',
            },
            {
                id: 'aholo-viewer',
                name: '高斯渲染',
                name_en: 'aholo-viewer',
                author: 'AUTO',
                openUrl: 'https://aholojs.dev/zh-CN/',
                githubUrl: 'https://github.com/manycoretech/aholo-viewer',
                image: HOST + 'images/aholo-viewer.webp',
            },
{
                id: 'comfort-website',
                name: '3d主页网站',
                name_en: 'comfort-website',
                author: 'AUTO',
                openUrl: 'https://john-and-patricias-romantic-comfort.vercel.app/',
                githubUrl: 'https://github.com/andrewwoan/john-and-patricias-romantic-comfort-website',
                image: HOST + 'images/comfort-website.webp',
            },
{
                id: 'three-fenestra',
                name: 'three-fenestra',
                name_en: 'three-fenestra',
                author: 'AUTO',
                openUrl: 'https://three-fenestra.codedgar.com/',
                githubUrl: 'https://github.com/codedgar/three-fenestra',
                image: HOST + 'images/three-fenestra.webp',
            },
{
                id: 'cymatics-labs',
                name: '音频粒子',
                name_en: 'cymatics-labs',
                author: 'AUTO',
                openUrl: 'https://cymatics-labs.vercel.app/',
                githubUrl: 'https://github.com/Sidmaz666/cymatics-labs',
                image: HOST + 'images/cymatics-labs.webp',
            },
{
                id: 'SysMocap',
                name: '数字虚拟人',
                name_en: 'SysMocap',
                author: 'AUTO',
                openUrl: 'https://github.com/xianfei/SysMocap',
                githubUrl: 'https://github.com/xianfei/SysMocap',
                image: HOST + 'images/SysMocap.webp',
            },
{
                id: 'demo-threejs-chinamap',
                name: '下钻地图',
                name_en: 'demo-threejs-chinamap',
                author: 'AUTO',
                openUrl: 'https://github.com/chemistwang/demo-threejs-chinamap',
                githubUrl: 'https://github.com/chemistwang/demo-threejs-chinamap',
                image: HOST + 'images/demo-threejs-chinamap.webp',
            },
{
                id: 'gta7',
                name: 'gta7',
                name_en: 'gta7',
                author: 'AUTO',
                openUrl: 'https://depixeled-chris.github.io/gta7/',
                githubUrl: 'https://github.com/depixeled-chris/gta7',
                image: HOST + 'images/gta7.webp',
            },
{
                id: 'cat-planet',
                name: 'cat-planet',
                name_en: 'cat-planet',
                author: 'AUTO',
                openUrl: 'https://qq598516797-dotcom.github.io/cat-planet/',
                githubUrl: 'https://github.com/qq598516797-dotcom/cat-planet',
                image: HOST + 'images/cat-planet.webp',
            },
{
                id: 'house-builder',
                name: 'house-builder',
                name_en: 'house-builder',
                author: 'AUTO',
                openUrl: 'https://ch-bas.github.io/threejs-sims-house-builder/',
                githubUrl: 'https://github.com/ch-bas/threejs-sims-house-builder',
                image: HOST + 'images/house-builder.webp',
            },
{
                id: 'tang-changan',
                name: 'tang-changan',
                name_en: 'tang-changan',
                author: 'AUTO',
                openUrl: 'https://github.com/andyhuo520/tang-changan',
                githubUrl: 'https://github.com/andyhuo520/tang-changan',
                image: HOST + 'images/tang-changan.webp',
            },
{
                id: 'Rose_flower',
                name: 'Rose_flower',
                name_en: 'Rose_flower',
                author: 'AUTO',
                openUrl: 'https://wake-bikila-dev.github.io/Rose_flower/',
                githubUrl: 'https://github.com/wake-bikila-dev/Rose_flower',
                image: HOST + 'images/Rose_flower.webp',
            },
            {
                id: 'dtilesConverter',
                name: '3dtiles Converter',
                name_en: '3dtiles Converter',
                author: 'AUTO',
                openUrl: 'https://github.com/fanvanzh/3dtiles',
                githubUrl: 'https://github.com/fanvanzh/3dtiles',
                image: HOST + 'images/3dtiles%20Converter.webp',
            },
            {
                id: 'mma-lab',
                name: 'mma-lab',
                name_en: 'mma-lab',
                author: 'AUTO',
                openUrl: 'https://mma-lab.netlify.app/',
                githubUrl: 'https://github.com/elegantmonark/mma-lab',
                image: HOST + 'images/mma-lab.webp',
            },
        ]
    }
]